const sample = [
  {
    mt20id: { _text: "1" },
    prfnm: { _text: "공연1" },
    prfpdfrom: { _text: "2023-09-28" },
    prfpdto: { _text: "2023-10-03" },
    fcltynm: { _text: "포은아트홀" },
    poster: { _text: "https://image.yes24.com/goods/62151258/XL" },
    genrenm: { _text: "테스트" },
    prfstate: { _text: "공연중" },
    openrun: { _text: "Y" },
  },
  {
    mt20id: { _text: "2" },
    prfnm: { _text: "공연1" },
    prfpdfrom: { _text: "2023-09-28" },
    prfpdto: { _text: "2023-10-03" },
    fcltynm: { _text: "포은아트홀" },
    poster: { _text: "https://image.yes24.com/goods/62151258/XL" },
    genrenm: { _text: "테스트" },
    prfstate: { _text: "공연중" },
    openrun: { _text: "Y" },
  },
  {
    mt20id: { _text: "3" },
    prfnm: { _text: "공연1" },
    prfpdfrom: { _text: "2023-09-28" },
    prfpdto: { _text: "2023-10-03" },
    fcltynm: { _text: "포은아트홀" },
    poster: { _text: "https://image.yes24.com/goods/62151258/XL" },
    genrenm: { _text: "테스트" },
    prfstate: { _text: "공연중" },
    openrun: { _text: "Y" },
  },
  {
    mt20id: { _text: "4" },
    prfnm: { _text: "공연1" },
    prfpdfrom: { _text: "2023-09-28" },
    prfpdto: { _text: "2023-10-03" },
    fcltynm: { _text: "포은아트홀" },
    poster: { _text: "https://image.yes24.com/goods/62151258/XL" },
    genrenm: { _text: "테스트" },
    prfstate: { _text: "공연중" },
    openrun: { _text: "Y" },
  },
  {
    mt20id: { _text: "5" },
    prfnm: { _text: "공연1" },
    prfpdfrom: { _text: "2023-09-28" },
    prfpdto: { _text: "2023-10-03" },
    fcltynm: { _text: "포은아트홀" },
    poster: { _text: "https://image.yes24.com/goods/62151258/XL" },
    genrenm: { _text: "테스트" },
    prfstate: { _text: "공연중" },
    openrun: { _text: "Y" },
  },
  {
    mt20id: { _text: "6" },
    prfnm: { _text: "공연1" },
    prfpdfrom: { _text: "2023-09-28" },
    prfpdto: { _text: "2023-10-03" },
    fcltynm: { _text: "포은아트홀" },
    poster: { _text: "https://image.yes24.com/goods/62151258/XL" },
    genrenm: { _text: "테스트" },
    prfstate: { _text: "공연중" },
    openrun: { _text: "Y" },
  },
  {
    mt20id: { _text: "7" },
    prfnm: { _text: "공연1" },
    prfpdfrom: { _text: "2023-09-28" },
    prfpdto: { _text: "2023-10-03" },
    fcltynm: { _text: "포은아트홀" },
    poster: { _text: "https://image.yes24.com/goods/62151258/XL" },
    genrenm: { _text: "테스트" },
    prfstate: { _text: "공연중" },
    openrun: { _text: "Y" },
  },
  {
    mt20id: { _text: "8" },
    prfnm: { _text: "공연1" },
    prfpdfrom: { _text: "2023-09-28" },
    prfpdto: { _text: "2023-10-03" },
    fcltynm: { _text: "포은아트홀" },
    poster: { _text: "https://image.yes24.com/goods/62151258/XL" },
    genrenm: { _text: "테스트" },
    prfstate: { _text: "공연중" },
    openrun: { _text: "Y" },
  },
  {
    mt20id: { _text: "9" },
    prfnm: { _text: "공연1" },
    prfpdfrom: { _text: "2023-09-28" },
    prfpdto: { _text: "2023-10-03" },
    fcltynm: { _text: "포은아트홀" },
    poster: { _text: "https://image.yes24.com/goods/62151258/XL" },
    genrenm: { _text: "테스트" },
    prfstate: { _text: "공연중" },
    openrun: { _text: "Y" },
  },
  {
    mt20id: { _text: "10" },
    prfnm: { _text: "공연1" },
    prfpdfrom: { _text: "2023-09-28" },
    prfpdto: { _text: "2023-10-03" },
    fcltynm: { _text: "포은아트홀" },
    poster: { _text: "https://image.yes24.com/goods/62151258/XL" },
    genrenm: { _text: "테스트" },
    prfstate: { _text: "공연중" },
    openrun: { _text: "Y" },
  },
  {
    mt20id: { _text: "11" },
    prfnm: { _text: "공연1" },
    prfpdfrom: { _text: "2023-09-28" },
    prfpdto: { _text: "2023-10-03" },
    fcltynm: { _text: "포은아트홀" },
    poster: { _text: "https://image.yes24.com/goods/62151258/XL" },
    genrenm: { _text: "테스트" },
    prfstate: { _text: "공연중" },
    openrun: { _text: "Y" },
  },
];

export default sample;
